export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST'
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS'
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL'

export const ADMIN_CATEGORY_REQUEST = 'ADMIN_CATEGORY_REQUEST'
export const ADMIN_CATEGORY_SUCCESS = 'ADMIN_CATEGORY_SUCCESS'
export const ADMIN_CATEGORY_FAIL = 'ADMIN_CATEGORY_FAIL'

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL'

export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST'
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS'
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_FAIL'

export const POST_EDIT_CATEGORY_REQUEST = 'POST_EDIT_CATEGORY_REQUEST'
export const POST_EDIT_CATEGORY_SUCCESS = 'POST_EDIT_CATEGORY_SUCCESS'
export const POST_EDIT_CATEGORY_FAIL = 'POST_EDIT_CATEGORY_FAIL'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL'
