export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_SINGLE_SUCCESS = 'POST_SINGLE_SUCCESS'
export const POST_SINGLE_REQUEST = 'POST_SINGLE_REQUEST'
export const POST_SINGLE_FAIL = 'POST_SINGLE_FAIL'

export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_REQUEST = 'ALL_POST_REQUEST'
export const ALL_POST_FAIL = 'ALL_POST_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
