export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_SINGLE_SUCCESS = 'POST_SINGLE_SUCCESS'
export const POST_SINGLE_REQUEST = 'POST_SINGLE_REQUEST'
export const POST_SINGLE_FAIL = 'POST_SINGLE_FAIL'

export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_REQUEST = 'ALL_POST_REQUEST'
export const ALL_POST_FAIL = 'ALL_POST_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'
export const EDIT_POST_RESET = 'EDIT_POST_RESET'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'
export const UPDATE_POST_RESET = 'UPDATE_POST_RESET'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'
