export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'

export const SIMILAR_PRODUCT_REQUEST = 'SIMILAR_PRODUCT_REQUEST'
export const SIMILAR_PRODUCT_SUCCESS = 'SIMILAR_PRODUCT_SUCCESS'
export const SIMILAR_PRODUCT_FAIL = 'SIMILAR_PRODUCT_FAIL'

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST'
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS'
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL'

export const PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST'
export const PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS'
export const PRODUCT_CATEGORY_FAIL = 'PRODUCT_CATEGORY_FAIL'


