export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'

export const SIMILAR_PRODUCT_REQUEST = 'SIMILAR_PRODUCT_REQUEST'
export const SIMILAR_PRODUCT_SUCCESS = 'SIMILAR_PRODUCT_SUCCESS'
export const SIMILAR_PRODUCT_FAIL = 'SIMILAR_PRODUCT_FAIL'

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST'
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS'
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL'

export const PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST'
export const PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS'
export const PRODUCT_CATEGORY_FAIL = 'PRODUCT_CATEGORY_FAIL'

export const EDITORS_CHOICE_REQUEST = 'EDITORS_CHOICE_REQUEST'
export const EDITORS_CHOICE_SUCCESS = 'EDITORS_CHOICE_SUCCESS'
export const EDITORS_CHOICE_FAIL = 'EDITORS_CHOICE_FAIL'

export const ALL_APPS_REQUEST = 'ALL_APPS_REQUEST'
export const ALL_APPS_SUCCESS = 'ALL_APPS_SUCCESS'
export const ALL_APPS_FAIL = 'ALL_APPS_FAIL'

export const ADMIN_APPS_REQUEST = 'ADMIN_APPS_REQUEST'
export const ADMIN_APPS_SUCCESS = 'ADMIN_APPS_SUCCESS'
export const ADMIN_APPS_FAIL = 'ADMIN_APPS_FAIL'

export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL'
export const EDIT_PRODUCT_RESET = 'EDIT_PRODUCT_RESET'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'

export const ADMIN_APPROVE_REQUEST = 'ADMIN_APPROVE_REQUEST'
export const ADMIN_APPROVE_SUCCESS = 'ADMIN_APPROVE_SUCCESS'
export const ADMIN_APPROVE_FAIL = 'ADMIN_APPROVE_FAIL'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'
