export const SLIDER_LIST_REQUEST = 'SLIDER_LIST_REQUEST';
export const SLIDER_LIST_SUCCESS = 'SLIDER_LIST_SUCCESS';
export const SLIDER_LIST_FAIL = 'SLIDER_LIST_FAIL';

export const CREATE_SLIDER_REQUEST = 'CREATE_SLIDER_REQUEST';
export const CREATE_SLIDER_SUCCESS = 'CREATE_SLIDER_SUCCESS';
export const CREATE_SLIDER_FAIL = 'CREATE_SLIDER_FAIL';
export const CREATE_SLIDER_RESET = 'CREATE_SLIDER_RESET';

export const SLIDE_SHOW_REQUEST = 'SLIDE_SHOW_REQUEST';
export const SLIDE_SHOW_SUCCESS = 'SLIDE_SHOW_SUCCESS';
export const SLIDE_SHOW_FAIL = 'SLIDE_SHOW_FAIL';

export const DELETE_SLIDER_REQUEST = 'DELETE_SLIDER_REQUEST';
export const DELETE_SLIDER_SUCCESS = 'DELETE_SLIDER_SUCCESS';
export const DELETE_SLIDER_FAIL = 'DELETE_SLIDER_FAIL';
export const DELETE_SLIDER_RESET = 'DELETE_SLIDER_RESET';