export const USER_AUTH_START = 'USER_AUTH_START'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'
export const RESET = 'RESET'

export const LOGOUT = 'LOGOUT'

export const USER_REGISTER_START = 'USER_REGISTER_START'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const CHANGE_ROLE_REQUEST = 'CHANGE_ROLE_REQUEST'
export const CHANGE_ROLE_SUCCESS = 'CHANGE_ROLE_SUCCESS'
export const CHANGE_ROLE_FAIL = 'CHANGE_ROLE_FAIL'
